// const allStatesForTimeZone = [
//   "Africa/Abidjan",
//   "Africa/Accra",
//   "Africa/Addis_Ababa",
//   "Africa/Algiers",
//   "Africa/Bamako",
//   "Africa/Bangui",
//   "Africa/Banjul",
//   "Africa/Bissau",
//   "Africa/Blantyre",
//   "Africa/Brazzaville",
//   "Africa/Bujumbura",
//   "Africa/Cairo",
//   "Africa/Casablanca",
//   "Africa/Ceuta",
//   "Africa/Conakry",
//   "Africa/Dakar",
//   "Africa/Dar_es_Salaam",
//   "Africa/Djibouti",
//   "Africa/Douala",
//   "Africa/El_Aaiun",
//   "Africa/Freetown",
//   "Africa/Gaborone",
//   "Africa/Harare",
//   "Africa/Johannesburg",
//   "Africa/Juba",
//   "Africa/Kampala",
//   "Africa/Khartoum",
//   "Africa/Kigali",
//   "Africa/Kinshasa",
//   "Africa/Lagos",
//   "Africa/Libreville",
//   "Africa/Lome",
//   "Africa/Luanda",
//   "Africa/Lusaka",
//   "Africa/Malabo",
//   "Africa/Maputo",
//   "Africa/Maseru",
//   "Africa/Mbabane",
//   "Africa/Mogadishu",
//   "Africa/Monrovia",
//   "Africa/Nairobi",
//   "Africa/Niamey",
//   "Africa/Nouakchott",
//   "Africa/Ouagadougou",
//   "Africa/Porto-Novo",
//   "Africa/Sao_Tome",
//   "Africa/Tunis",
//   "Africa/Windhoek",
//   "America/Adak",
//   "America/Anchorage",
//   "America/Antigua",
//   "America/Araguaina",
//   "America/Argentina/La_Rioja",
//   "America/Argentina/Rio_Gallegos",
//   "America/Argentina/Salta",
//   "America/Argentina/Tucuman",
//   "America/Argentina/Ushuaia",
//   "America/Asuncion",
//   "America/Atikokan",
//   "America/Bahia",
//   "America/Bahia_Banderas",
//   "America/Barbados",
//   "America/Belem",
//   "America/Belize",
//   "America/Blanc-Sablon",
//   "America/Boa_Vista",
//   "America/Bogota",
//   "America/Boise",
//   "America/Cambridge_Bay",
//   "America/Campo_Grande",
//   "America/Cancun",
//   "America/Caracas",
//   "America/Cayenne",
//   "America/Chicago",
//   "America/Chihuahua",
//   "America/Colima",
//   "America/Costa_Rica",
//   "America/Creston",
//   "America/Dawson",
//   "America/Dawson_Creek",
//   "America/Denver",
//   "America/Detroit",
//   "America/Dominica",
//   "America/Edmonton",
//   "America/Eirunepe",
//   "America/El_Salvador",
//   "America/Fort_Nelson",
//   "America/Fort_Wayne",
//   "America/Guatemala",
//   "America/Guayaquil",
//   "America/Guyana",
//   "America/Halifax",
//   "America/Havana",
//   "America/Hermosillo",
//   "America/Indiana/Indianapolis",
//   "America/Indiana/Knox",
//   "America/Indiana/Marengo",
//   "America/Indiana/Petersburg",
//   "America/Indiana/Tell_City",
//   "America/Indiana/Vevay",
//   "America/Indiana/Winamac",
//   "America/Indianapolis",
//   "America/Isla_Man",
//   "America/Jamaica",
//   "America/Juneau",
//   "America/Kentucky/Louisville",
//   "America/Kentucky/Monticello",
//   "America/Kralendijk",
//   "America/Los_Angeles",
//   "America/Louisville",
//   "America/Maceio",
//   "America/Managua",
//   "America/Manaus",
//   "America/Martinique",
//   "America/Matamoros",
//   "America/Mazatlan",
//   "America/Mexico_City",
//   "America/Miquelon",
//   "America/Moncton",
//   "America/Montreal",
//   "America/Nassau",
//   "America/New_York",
//   "America/Nipigon",
//   "America/Nome",
//   "America/Noronha",
//   "America/North_Dakota/Beulah",
//   "America/North_Dakota/Center",
//   "America/North_Dakota/New_Salem",
//   "America/Ojinaga",
//   "America/Panama",
//   "America/Phoenix",
//   "America/Port-au-Prince",
//   "America/Port_of_Spain",
//   "America/Rankin_Inlet",
//   "America/Rainy_River",
//   "America/Regina",
//   "America/Resolute",
//   "America/Rio_Branco",
//   "America/Santarem",
//   "America/Santiago",
//   "America/Santo_Domingo",
//   "America/Sao_Paulo",
//   "America/Scoresbysund",
//   "America/Sitka",
//   "America/St_Johns",
//   "America/Tegucigalpa",
//   "America/Thule",
//   "America/Tijuana",
//   "America/Toronto",
//   "America/Tortola",
//   "America/Vancouver",
//   "America/Whitehorse",
//   "America/Winnipeg",
//   "America/Yakutat",
//   "America/Yellowknife",
//   "Antarctica/Casey",
//   "Antarctica/Davis",
//   "Antarctica/DumontDUrville",
//   "Antarctica/Macquarie",
//   "Antarctica/McMurdo",
//   "Antarctica/Palmer",
//   "Antarctica/Syowa",
//   "Antarctica/Troll",
//   "Antarctica/Vostok",
//   "Arctic/Longyearbyen",
//   "Asia/Aden",
//   "Asia/Almaty",
//   "Asia/Amman",
//   "Asia/Aqtau",
//   "Asia/Aqtobe",
//   "Asia/Ashgabat",
//   "Asia/Baghdad",
//   "Asia/Baku",
//   "Asia/Bangkok",
//   "Asia/Barnaul",
//   "Asia/Beirut",
//   "Asia/Bishkek",
//   "Asia/Brunei",
//   "Asia/Chita",
//   "Asia/Choibalsan",
//   "Asia/Colombo",
//   "Asia/Dhaka",
//   "Asia/Dubai",
//   "Asia/Dushanbe",
//   "Asia/Gaza",
//   "Asia/Hong_Kong",
//   "Asia/Irkutsk",
//   "Asia/Jakarta",
//   "Asia/Jayapura",
//   "Asia/Jerusalem",
//   "Asia/Kabul",
//   "Asia/Kamchatka",
//   "Asia/Kathmandu",
//   "Asia/Kolkata",
//   "Asia/Manila",
//   "Asia/Muscat",
//   "Asia/Nicosia",
//   "Asia/Novosibirsk",
//   "Asia/Omsk",
//   "Asia/Oral",
//   "Asia/Phnom_Penh",
//   "Asia/Pontianak",
//   "Asia/Qatar",
//   "Asia/Qyzylorda",
//   "Asia/Riyadh",
//   "Asia/Sakhalin",
//   "Asia/Samarkand",
//   "Asia/Shanghai",
//   "Asia/Singapore",
//   "Asia/Taipei",
//   "Asia/Tashkent",
//   "Asia/Tbilisi",
//   "Asia/Tehran",
//   "Asia/Thimphu",
//   "Asia/Tokyo",
//   "Asia/Ulaanbaatar",
//   "Asia/Urumqi",
//   "Asia/Vientiane",
//   "Asia/Yangon",
//   "Asia/Yekaterinburg",
//   "Asia/Zhangjiajie",
//   "Atlantic/Azores",
//   "Atlantic/Bermuda",
//   "Atlantic/Canary",
//   "Atlantic/Cape_Verde",
//   "Atlantic/Faeroe",
//   "Atlantic/Jan_Mayen",
//   "Atlantic/Madeira",
//   "Atlantic/Reykjavik",
//   "Atlantic/South_Georgia",
//   "Atlantic/St_Helena",
//   "Australia/Adelaide",
//   "Australia/Brisbane",
//   "Australia/Broken_Hill",
//   "Australia/Darwin",
//   "Australia/Eucla",
//   "Australia/Hobart",
//   "Australia/Lindeman",
//   "Australia/Lord_Howe",
//   "Australia/Melbourne",
//   "Australia/Perth",
//   "Australia/Sydney",
//   "Australia/Queensland",
//   "Australia/South",
//   "Australia/Tasmania",
//   "Australia/West",
//   "Etc/GMT",
//   "Etc/GMT+0",
//   "Etc/GMT+1",
//   "Etc/GMT+10",
//   "Etc/GMT+11",
//   "Etc/GMT+12",
//   "Etc/GMT-1",
//   "Etc/GMT-10",
//   "Etc/GMT-11",
//   "Etc/GMT-12",
//   "Etc/GMT-2",
//   "Etc/GMT-3",
//   "Etc/GMT-4",
//   "Etc/GMT-5",
//   "Etc/GMT-6",
//   "Etc/GMT-7",
//   "Etc/GMT-8",
//   "Etc/GMT-9",
//   "Etc/GMT0",
//   "Etc/GMT0+1",
//   "Etc/GMT0+10",
//   "Etc/GMT0+11",
//   "Etc/GMT0+12",
//   "Etc/GMT0-1",
//   "Etc/GMT0-10",
//   "Etc/GMT0-11",
//   "Etc/GMT0-12",
//   "Etc/GMT0-2",
//   "Etc/GMT0-3",
//   "Etc/GMT0-4",
//   "Etc/GMT0-5",
//   "Etc/GMT0-6",
//   "Etc/GMT0-7",
//   "Etc/GMT0-8",
//   "Etc/GMT0-9",
//   "Etc/GMT+2",
//   "Etc/GMT+3",
//   "Etc/GMT+4",
//   "Etc/GMT+5",
//   "Etc/GMT+6",
//   "Etc/GMT+7",
//   "Etc/GMT+8",
//   "Etc/GMT+9",
//   "Etc/GMT+10",
//   "Etc/GMT+11",
//   "Etc/GMT+12",
//   "Etc/GMT-1",
//   "Etc/GMT-2",
//   "Etc/GMT-3",
//   "Etc/GMT-4",
//   "Etc/GMT-5",
//   "Etc/GMT-6",
//   "Etc/GMT-7",
//   "Etc/GMT-8",
//   "Etc/GMT-9",
//   "Europe/Amsterdam",
//   "Europe/Andorra",
//   "Europe/Athens",
//   "Europe/Belgrade",
//   "Europe/Berlin",
//   "Europe/Bratislava",
//   "Europe/Brussels",
//   "Europe/Bucharest",
//   "Europe/Budapest",
//   "Europe/Busingen",
//   "Europe/Chisinau",
//   "Europe/Copenhagen",
//   "Europe/Dublin",
//   "Europe/Gibraltar",
//   "Europe/Guernsey",
//   "Europe/Helsinki",
//   "Europe/Isle_of_Man",
//   "Europe/Istanbul",
//   "Europe/Jersey",
//   "Europe/Kaliningrad",
//   "Europe/Kiev",
//   "Europe/Kosice",
//   "Europe/Lisbon",
//   "Europe/Ljubljana",
//   "Europe/London",
//   "Europe/Luxembourg",
//   "Europe/Madrid",
//   "Europe/Malta",
//   "Europe/Mariehamn",
//   "Europe/Minsk",
//   "Europe/Monaco",
//   "Europe/Moscow",
//   "Europe/Nicosia",
//   "Europe/Oslo",
//   "Europe/Paris",
//   "Europe/Podgorica",
//   "Europe/Prague",
//   "Europe/Riga",
//   "Europe/Rome",
//   "Europe/Samara",
//   "Europe/San_Marino",
//   "Europe/Sarajevo",
//   "Europe/Sofia",
//   "Europe/Stockholm",
//   "Europe/Tallinn",
//   "Europe/Tirane",
//   "Europe/Tiraspol",
//   "Europe/Uzhgorod",
//   "Europe/Vaduz",
//   "Europe/Vatican",
//   "Europe/Vienna",
//   "Europe/Vilnius",
//   "Europe/Warsaw",
//   "Europe/Zagreb",
//   "Europe/Zaporozhye",
//   "Europe/Zurich",
//   "Indian/Antananarivo",
//   "Indian/Chagos",
//   "Indian/Christmas",
//   "Indian/Cocos",
//   "Indian/Comoro",
//   "Indian/Kerguelen",
//   "Indian/Mahe",
//   "Indian/Maldives",
//   "Indian/Mauritius",
//   "Indian/Mayotte",
//   "Indian/Reunion",
//   "Pacific/Apia",
//   "Pacific/Auckland",
//   "Pacific/Bougainville",
//   "Pacific/Chatham",
//   "Pacific/Chuuk",
//   "Pacific/Easter",
//   "Pacific/Efate",
//   "Pacific/Enderbury",
//   "Pacific/Fakaofo",
//   "Pacific/Fiji",
//   "Pacific/Galapagos",
//   "Pacific/Gambier",
//   "Pacific/Guadalcanal",
//   "Pacific/Guam",
//   "Pacific/Honolulu",
//   "Pacific/Kiritimati",
//   "Pacific/Kosrae",
//   "Pacific/Majuro",
//   "Pacific/Marquesas",
//   "Pacific/Midway",
//   "Pacific/Nauru",
//   "Pacific/Niue",
//   "Pacific/Norfolk",
//   "Pacific/Noumea",
//   "Pacific/Pago_Pago",
//   "Pacific/Palau",
//   "Pacific/Pitcairn",
//   "Pacific/Port_Moresby",
//   "Pacific/Rarotonga",
//   "Pacific/Saipan",
//   "Pacific/Tahiti",
//   "Pacific/Tarawa",
//   "Pacific/Tongatapu",
//   "Pacific/Wake",
//   "Pacific/Wallis",
//   "Pacific/Wallis_Futuna",
//   "Poland",
//   "US/Alaska",
//   "US/Aleutian",
//   "US/Arizona",
//   "US/Central",
//   "US/Eastern",
//   "US/Hawaii",
//   "US/Mountain",
//   "US/Pacific",
//   "US/Samoa",
//   "Pacific/Kwajalein",
//   "Pacific/Midway",
//   "Pacific/Honolulu",
//   "America/Anchorage",
//   "America/Los_Angeles",
//   "America/Denver",
//   "America/Chicago",
//   "America/New_York",
//   "America/Halifax",
//   "America/Argentina/Buenos_Aires",
//   "Atlantic/South_Georgia",
//   "Atlantic/Azores",
//   "Europe/London",
//   "Europe/Paris",
//   "Europe/Bucharest",
//   "Europe/Moscow",
//   "Asia/Dubai",
//   "Asia/Karachi",
//   "Asia/Dhaka",
//   "Asia/Bangkok",
//   "Asia/Singapore",
//   "Asia/Tokyo",
//   "Australia/Sydney",
//   "Pacific/Guadalcanal",
//   "Pacific/Fiji",
// ];

const allStatesForTimeZone = [
  {
    zone: "Pacific/Midway",
    gmt: "(GMT-11:00)",
    name: "Midway Island",
  },
  {
    zone: "US/Samoa",
    gmt: "(GMT-11:00)",
    name: "Samoa",
  },
  {
    zone: "US/Hawaii",
    gmt: "(GMT-10:00)",
    name: "Hawaii",
  },
  {
    zone: "US/Alaska",
    gmt: "(GMT-09:00)",
    name: "Alaska",
  },
  {
    zone: "US/Pacific",
    gmt: "(GMT-08:00)",
    name: "Pacific Time (US &amp; Canada)",
  },
  {
    zone: "America/Tijuana",
    gmt: "(GMT-08:00)",
    name: "Tijuana",
  },
  {
    zone: "US/Arizona",
    gmt: "(GMT-07:00)",
    name: "Arizona",
  },
  {
    zone: "US/Mountain",
    gmt: "(GMT-07:00)",
    name: "Mountain Time (US &amp; Canada)",
  },
  {
    zone: "America/Chihuahua",
    gmt: "(GMT-07:00)",
    name: "Chihuahua",
  },
  {
    zone: "America/Mazatlan",
    gmt: "(GMT-07:00)",
    name: "Mazatlan",
  },
  {
    zone: "America/Mexico_City",
    gmt: "(GMT-06:00)",
    name: "Mexico City",
  },
  {
    zone: "America/Monterrey",
    gmt: "(GMT-06:00)",
    name: "Monterrey",
  },
  {
    zone: "Canada/Saskatchewan",
    gmt: "(GMT-06:00)",
    name: "Saskatchewan",
  },
  {
    zone: "US/Central",
    gmt: "(GMT-06:00)",
    name: "Central Time (US &amp; Canada)",
  },
  {
    zone: "US/Eastern",
    gmt: "(GMT-05:00)",
    name: "Eastern Time (US &amp; Canada)",
  },
  {
    zone: "US/East-Indiana",
    gmt: "(GMT-05:00)",
    name: "Indiana (East)",
  },
  {
    zone: "America/Bogota",
    gmt: "(GMT-05:00)",
    name: "Bogota",
  },
  {
    zone: "America/Lima",
    gmt: "(GMT-05:00)",
    name: "Lima",
  },
  {
    zone: "America/Caracas",
    gmt: "(GMT-04:30)",
    name: "Caracas",
  },
  {
    zone: "Canada/Atlantic",
    gmt: "(GMT-04:00)",
    name: "Atlantic Time (Canada)",
  },
  {
    zone: "America/La_Paz",
    gmt: "(GMT-04:00)",
    name: "La_Paz",
  },
  {
    zone: "America/Santiago",
    gmt: "(GMT-04:00)",
    name: "Santiago",
  },
  {
    zone: "Canada/Newfoundland",
    gmt: "(GMT-03:30)",
    name: "Newfoundland",
  },
  {
    zone: "America/Buenos_Aires",
    gmt: "(GMT-03:00)",
    name: "Buenos Aires",
  },
  {
    zone: "Greenland",
    gmt: "(GMT-03:00)",
    name: "Greenland",
  },
  {
    zone: "Atlantic/Stanley",
    gmt: "(GMT-02:00)",
    name: "Stanley",
  },
  {
    zone: "Atlantic/Azores",
    gmt: "(GMT-01:00)",
    name: "Azores",
  },
  {
    zone: "Atlantic/Cape_Verde",
    gmt: "(GMT-01:00)",
    name: "Cape Verde Is.",
  },
  {
    zone: "Africa/Casablanca",
    gmt: "(GMT)",
    name: "Casablanca",
  },
  {
    zone: "Europe/Dublin",
    gmt: "(GMT)",
    name: "Dublin",
  },
  {
    zone: "Europe/Lisbon",
    gmt: "(GMT)",
    name: "Libson",
  },
  {
    zone: "Europe/London",
    gmt: "(GMT)",
    name: "London",
  },
  {
    zone: "Africa/Monrovia",
    gmt: "(GMT)",
    name: "Monrovia",
  },
  {
    zone: "Europe/Amsterdam",
    gmt: "(GMT+01:00)",
    name: "Amsterdam",
  },
  {
    zone: "Europe/Belgrade",
    gmt: "(GMT+01:00)",
    name: "Belgrade",
  },
  {
    zone: "Europe/Berlin",
    gmt: "(GMT+01:00)",
    name: "Berlin",
  },
  {
    zone: "Europe/Bratislava",
    gmt: "(GMT+01:00)",
    name: "Bratislava",
  },
  {
    zone: "Europe/Brussels",
    gmt: "(GMT+01:00)",
    name: "Brussels",
  },
  {
    zone: "Europe/Budapest",
    gmt: "(GMT+01:00)",
    name: "Budapest",
  },
  {
    zone: "Europe/Copenhagen",
    gmt: "(GMT+01:00)",
    name: "Copenhagen",
  },
  {
    zone: "Europe/Ljubljana",
    gmt: "(GMT+01:00)",
    name: "Ljubljana",
  },
  {
    zone: "Europe/Madrid",
    gmt: "(GMT+01:00)",
    name: "Madrid",
  },
  {
    zone: "Europe/Paris",
    gmt: "(GMT+01:00)",
    name: "Paris",
  },
  {
    zone: "Europe/Prague",
    gmt: "(GMT+01:00)",
    name: "Prague",
  },
  {
    zone: "Europe/Rome",
    gmt: "(GMT+01:00)",
    name: "Rome",
  },
  {
    zone: "Europe/Sarajevo",
    gmt: "(GMT+01:00)",
    name: "Sarajevo",
  },
  {
    zone: "Europe/Skopje",
    gmt: "(GMT+01:00)",
    name: "Skopje",
  },
  {
    zone: "Europe/Stockholm",
    gmt: "(GMT+01:00)",
    name: "Stockholm",
  },
  {
    zone: "Europe/Vienna",
    gmt: "(GMT+01:00)",
    name: "Vienna",
  },
  {
    zone: "Europe/Warsaw",
    gmt: "(GMT+01:00)",
    name: "Warsaw",
  },
  {
    zone: "Europe/Zagreb",
    gmt: "(GMT+01:00)",
    name: "Zagreb",
  },
  {
    zone: "Europe/Athens",
    gmt: "(GMT+02:00)",
    name: "Athens",
  },
  {
    zone: "Europe/Bucharest",
    gmt: "(GMT+02:00)",
    name: "Bucharest",
  },
  {
    zone: "Africa/Cairo",
    gmt: "(GMT+02:00)",
    name: "Cairo",
  },
  {
    zone: "Africa/Harare",
    gmt: "(GMT+02:00)",
    name: "Harere",
  },
  {
    zone: "Europe/Helsinki",
    gmt: "(GMT+02:00)",
    name: "Helsinki",
  },
  {
    zone: "Europe/Istanbul",
    gmt: "(GMT+02:00)",
    name: "Istanbul",
  },
  {
    zone: "Asia/Jerusalem",
    gmt: "(GMT+02:00)",
    name: "Jerusalem",
  },
  {
    zone: "Europe/Kiev",
    gmt: "(GMT+02:00)",
    name: "Kiev",
  },
  {
    zone: "Europe/Minsk",
    gmt: "(GMT+02:00)",
    name: "Minsk",
  },
  {
    zone: "Europe/Riga",
    gmt: "(GMT+02:00)",
    name: "Riga",
  },
  {
    zone: "Europe/Sofia",
    gmt: "(GMT+02:00)",
    name: "Sofia",
  },
  {
    zone: "Europe/Tallinn",
    gmt: "(GMT+02:00)",
    name: "Tallinn",
  },
  {
    zone: "Europe/Vilnius",
    gmt: "(GMT+02:00)",
    name: "Vilnius",
  },
  {
    zone: "Asia/Baghdad",
    gmt: "(GMT+03:00)",
    name: "Baghdad",
  },
  {
    zone: "Asia/Kuwait",
    gmt: "(GMT+03:00)",
    name: "Kuwait",
  },
  {
    zone: "Africa/Nairobi",
    gmt: "(GMT+03:00)",
    name: "Nairobi",
  },
  {
    zone: "Asia/Riyadh",
    gmt: "(GMT+03:00)",
    name: "Riyadh",
  },
  {
    zone: "Asia/Tehran",
    gmt: "(GMT+03:30)",
    name: "Tehran",
  },
  {
    zone: "Europe/Moscow",
    gmt: "(GMT+04:00)",
    name: "Moscow",
  },
  {
    zone: "Asia/Baku",
    gmt: "(GMT+04:00)",
    name: "Baku",
  },
  {
    zone: "Europe/Volgograd",
    gmt: "(GMT+04:00)",
    name: "Volgograd",
  },
  {
    zone: "Asia/Muscat",
    gmt: "(GMT+04:00)",
    name: "Muscat",
  },
  {
    zone: "Asia/Tbilisi",
    gmt: "(GMT+04:00)",
    name: "Tbilisi",
  },
  {
    zone: "Asia/Yerevan",
    gmt: "(GMT+04:00)",
    name: "Yerevan",
  },
  {
    zone: "Asia/Kabul",
    gmt: "(GMT+04:30)",
    name: "Kabul",
  },
  {
    zone: "Asia/Karachi",
    gmt: "(GMT+05:00)",
    name: "Karachi",
  },
  {
    zone: "Asia/Tashkent",
    gmt: "(GMT+05:00)",
    name: "Tashkent",
  },
  {
    zone: "Asia/Kolkata",
    gmt: "(GMT+05:30)",
    name: "Kolkata",
  },
  {
    zone: "Asia/Kathmandu",
    gmt: "(GMT+05:45)",
    name: "Kathmandu",
  },
  {
    zone: "Asia/Yekaterinburg",
    gmt: "(GMT+06:00)",
    name: "Yekaterinburg",
  },
  {
    zone: "Asia/Almaty",
    gmt: "(GMT+06:00)",
    name: "Almaty",
  },
  {
    zone: "Asia/Dhaka",
    gmt: "(GMT+06:00)",
    name: "Dhaka",
  },
  {
    zone: "Asia/Novosibirsk",
    gmt: "(GMT+07:00)",
    name: "Novosibirsk",
  },
  {
    zone: "Asia/Bangkok",
    gmt: "(GMT+07:00)",
    name: "Bangkok",
  },
  {
    zone: "Asia/Jakarta",
    gmt: "(GMT+07:00)",
    name: "Jakarta",
  },
  {
    zone: "Asia/Krasnoyarsk",
    gmt: "(GMT+08:00)",
    name: "Krasnoyarsk",
  },
  {
    zone: "Asia/Chongqing",
    gmt: "(GMT+08:00)",
    name: "Chongqing",
  },
  {
    zone: "Asia/Hong_Kong",
    gmt: "(GMT+08:00)",
    name: "Hong Kong",
  },
  {
    zone: "Asia/Kuala_Lumpur",
    gmt: "(GMT+08:00)",
    name: "Kuala Lumpur",
  },
  {
    zone: "Australia/Perth",
    gmt: "(GMT+08:00)",
    name: "Perth",
  },
  {
    zone: "Asia/Singapore",
    gmt: "(GMT+08:00)",
    name: "Singapore",
  },
  {
    zone: "Asia/Taipei",
    gmt: "(GMT+08:00)",
    name: "Taipei",
  },
  {
    zone: "Asia/Ulaanbaatar",
    gmt: "(GMT+08:00)",
    name: "Ulaan Bataar",
  },
  {
    zone: "Asia/Urumqi",
    gmt: "(GMT+08:00)",
    name: "Urumqi",
  },
  {
    zone: "Asia/Irkutsk",
    gmt: "(GMT+09:00)",
    name: "Irkutsk",
  },
  {
    zone: "Asia/Seoul",
    gmt: "(GMT+09:00)",
    name: "Seoul",
  },
  {
    zone: "Asia/Tokyo",
    gmt: "(GMT+09:00)",
    name: "Tokyo",
  },
  {
    zone: "Australia/Adelaide",
    gmt: "(GMT+09:30)",
    name: "Adelaide",
  },
  {
    zone: "Australia/Darwin",
    gmt: "(GMT+09:30)",
    name: "Darwin",
  },
  {
    zone: "Asia/Yakutsk",
    gmt: "(GMT+10:00)",
    name: "Yakutsk",
  },
  {
    zone: "Australia/Brisbane",
    gmt: "(GMT+10:00)",
    name: "Brisbane",
  },
  {
    zone: "Australia/Canberra",
    gmt: "(GMT+10:00)",
    name: "Canberra",
  },
  {
    zone: "Pacific/Guam",
    gmt: "(GMT+10:00)",
    name: "Guam",
  },
  {
    zone: "Australia/Hobart",
    gmt: "(GMT+10:00)",
    name: "Hobart",
  },
  {
    zone: "Australia/Melbourne",
    gmt: "(GMT+10:00)",
    name: "Melbourne",
  },
  {
    zone: "Pacific/Port_Moresby",
    gmt: "(GMT+10:00)",
    name: "Port Moresby",
  },
  {
    zone: "Australia/Sydney",
    gmt: "(GMT+10:00)",
    name: "Sydney",
  },
  {
    zone: "Asia/Vladivostok",
    gmt: "(GMT+11:00)",
    name: "Vladivostok",
  },
  {
    zone: "Asia/Magadan",
    gmt: "(GMT+12:00)",
    name: "Magadan",
  },
  {
    zone: "Pacific/Auckland",
    gmt: "(GMT+12:00)",
    name: "Auckland",
  },
  {
    zone: "Pacific/Fiji",
    gmt: "(GMT+12:00)",
    name: "Fiji",
  },
];

export default allStatesForTimeZone;
